# Build settings
markdown: redcarpet
highlighter: pygments
gems:
  - jemoji

# Site settings
title: "Jacques de Vos"
description: > # this means to ignore newlines until "email:"
   Experiments and experiences in software.

email: jacques@nreality.com
#blog logo
logo: "/assets/images/jacdevos300x300.png"
# blog cover
cover: "/assets/images/moz1024x512.jpg"

name: 'Jacques de Vos'
author: 'Jacques de Vos'
author_image: "/assets/images/jacdevos300x300.png"

paginate:	10

url: "http://jacques.nreality.com" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@jacdevos'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/jacdevos
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/jacdevos
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/jacdevos
    desc:	Connect on LinkedIn
#    share_url:
#    share_title:
#    share_link:
