# Site settings
title:          "Jacques de Vos"
description:    "Experiments and experiences in software."
email:          jacques@nreality.com
url:            "https://jacques.nreality.com"
baseurl:        ""
twitter_handle: "@jacdevos"

# Author
author:
  name:         Jacques de Vos
  email:        jacques@nreality.com

# Social
social:
  - icon:   twitter
    url:    https://twitter.com/jacdevos
    desc:   Follow me on twitter
  - icon:   github
    url:    https://github.com/jacdevos
    desc:   Fork me on github
  - icon:   linkedin
    url:    https://www.linkedin.com/in/jacdevos
    desc:   Connect on LinkedIn

# Theme
remote_theme: chesterhow/tale

# Build settings
markdown:       kramdown
highlighter:    rouge
permalink:      /:year-:month-:day/:title
paginate:       50

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-remote-theme

# Includes
include:
  - _pages

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - vendor
